# react dev server

# vite.config.js
# export default defineConfig({
#   plugins: [react()],
#   server: {
#     port: 3210,
#     host: '0.0.0.0'
#   },
#   ...
# })

services:
  react:
    container_name: react_dev_server
    image: node:latest
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "3210:3210"
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: bash -c "npm install && npm run dev"